name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: |
        gradle wrapper
        ./gradlew clean build
